name: flutter_hooks_lint_plugin_plus_workspace
description: Workspace for flutter_hooks_lint_plugin_plus
version: 1.0.0

workspace:
  - flutter_hooks_lint_plugin_plus
  - lint_tester

environment:
  sdk: ">=3.6.0 <4.0.0"

dev_dependencies:
  melos: ^6.0.0
