analyzer:
  errors:
    unused_local_variable: ignore
  plugins:
    - custom_lint

custom_lint:
  rules:
    - hooks_exhaustive_deps:
        constant_hooks:
          - useRef
          - useIsMounted
          - useFocusNode
          - useContext
          - useConstantValue
    - hooks_no_nested_usage
