name: flutter_hooks_lint_plugin_plus
description: A custom_lint plugin for Flutter Hooks that provides lint rules for hook usage best practices
version: 0.0.1
repository: https://github.com/akaboshinit/flutter_hooks_lint_plugin_plus

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.7.0
  custom_lint_builder: ^0.7.0

dev_dependencies:
  test: ^1.24.0
  custom_lint: ^0.7.0
